---
- name: install packages
  hosts: all
  tasks:
  - name: install yum
    yum:
         name: "{{ item }}"
         state: installed
    with_items:
      - git
      - wget
      - telnet
      - make
      - gcc    
