---
- name: To excecute httpd on redhat and ubuntu
  hosts: all
  become: true
  vars: 
    port: 8082  
  tasks:

  - name: To install httpd on Redhat
    yum: "name=httpd state=installed"
    when: ansible_os_family == "RedHat"
    notify: start httpd service

  - name: To install apache2 on Debian
    apt: "name=apache2 state=present"
    when: ansible_os_family == "Debian"
    notify: start apache2 service    

  - name: To copy index.html file
    copy: 
      src: /home/ansible/index.html
      dest: /var/www/html
      mode: 0666  
  
  - name: To change the port 
    lineinfile:
      path: /etc/httpd/conf/httpd.conf
      regexp: '^Listen '
      insertafter: '^#Listen '
      line: Listen {{ port }}    
    when: ansible_os_family == "RedHat"
    notify: restart httpd service  

  - name: To change the port on ubuntu
    lineinfile:
      path: /etc/apache2/ports.conf
      regexp: '^Listen '
      insertafter: "# /etc/apache2/sites-enabled/000-default.conf"
      line: Listen {{ port }}
    when: ansible_os_family == 'Debian'
    notify: restart apache service  

  handlers:
  
  - name: start httpd service  
    service: "name=httpd state=started"

  - name: start apache2 service
    service: "name=apache2 state=started"

  - name: restart httpd service
    service: "name=httpd state=restarted"

  - name: restart apache service
    service: "name=apache2 state=restarted"    

      
