---
# tasks file for roles_htppd
  - name: To install httpd on Redhat
    yum: "name=httpd state=installed"
    when: ansible_os_family == "RedHat"
    notify: start httpd service

  - name: To install apache2 on Debian
    apt: "name=apache2 state=present"
    when: ansible_os_family == "Debian"
    notify: start apache2 service

  - name: To copy index.html file
    copy:
      src: /home/ansible/index.html
      dest: /var/www/html
      owner: 0666  

  - name: To change the port
    lineinfile:
      path: /etc/httpd/conf/httpd.conf
      regexp: '^Listen '
      insertafter: '^#Listen '
      line: Listen {{ port }}
    when: ansible_os_family == "RedHat"
    notify: restart httpd service

  - name: To change the port on ubuntu
    lineinfile:
      path: /etc/apache2/ports.conf
      regexp: '^Listen '
      insertafter: "# /etc/apache2/sites-enabled/000-default.conf"
      line: Listen {{ port }}
    when: ansible_os_family == 'Debian'
    notify: restart apache service

